spring:
    profiles:
        active: sit
    datasource:
        url: jdbc:mysql://database-url
        username: icax-db
        password: T09riow
    banner:
        charset: UTF-8
        location: classpath:robot-inventory-banner.txt
server:
    servlet:
        context-path: /api/v1